web/router.ex
defmodule HostelManagement.Router do
  use HostelManagement.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HostelManagement do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/tenants", TenantController do 
      post "/rent", TenantController, :add_rent
    end
    resources "/users", UserController, only: [:show, :new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", HostelManagement do
  #   pipe_through :api
  # end
end

web/models/tenant.ex
defmodule HostelManagement.Tenant do
  use HostelManagement.Web, :model

  schema "tenants" do
    field :name, :string
    field :email, :string
    field :contact_number, :string

    has_many :rents, HostelManagement.Rent

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :email, :contact_number])
    |> validate_required([:name, :email, :contact_number])
  end
end

web/controllers/tenant_controller.ex
defmodule HostelManagement.TenantController do
  use HostelManagement.Web, :controller

  alias HostelManagement.Tenant
  alias HostelManagement.Rent

  plug :scrub_params, "rent" when action in [:add_rent]

  def index(conn, _params) do
    tenants = Repo.all(Tenant)
    render(conn, "index.html", tenants: tenants)
  end

  def new(conn, _params) do
    changeset = Tenant.changeset(%Tenant{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"tenant" => tenant_params}) do
    changeset = Tenant.changeset(%Tenant{}, tenant_params)

    case Repo.insert(changeset) do
      {:ok, _tenant} ->
        conn
        |> put_flash(:info, "Tenant created successfully.")
        |> redirect(to: tenant_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    tenant = Repo.get(Tenant, id) |> Repo.preload([:rents])
    changeset = Rent.changeset(%Rent{})
    render(conn, "show.html", tenant: tenant, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    tenant = Repo.get!(Tenant, id)
    changeset = Tenant.changeset(tenant)
    render(conn, "edit.html", tenant: tenant, changeset: changeset)
  end

  def update(conn, %{"id" => id, "tenant" => tenant_params}) do
    tenant = Repo.get!(Tenant, id)
    changeset = Tenant.changeset(tenant, tenant_params)

    case Repo.update(changeset) do
      {:ok, tenant} ->
        conn
        |> put_flash(:info, "Tenant updated successfully.")
        |> redirect(to: tenant_path(conn, :show, tenant))
      {:error, changeset} ->
        render(conn, "edit.html", tenant: tenant, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    tenant = Repo.get!(Tenant, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(tenant)

    conn
    |> put_flash(:info, "Tenant deleted successfully.")
    |> redirect(to: tenant_path(conn, :index))
  end

  def add_rent(conn, %{"rent" => rent_params, "tenant_id" => tenant_id}) do
    fix_date = fn(date_string) -> [month, day, year] = String.split(date_string, "/"); %{"month" => month, "day" => day, "year" => year} end
    fixed_rent_param = rent_params
    |> Map.update!("start_date", fix_date)
    |> Map.update!("end_date", fix_date)

    changeset = Rent.changeset(%Rent{}, Map.put(fixed_rent_param, "tenant_id", tenant_id))
    IO.puts "**********************"
    IO.inspect Map.put(fixed_rent_param, "tenant_id", tenant_id)
    tenant = Tenant |> Repo.get(tenant_id) |> Repo.preload([:rents])

      if changeset.valid? do
        Repo.insert(changeset)

        conn
        |> put_flash(:info, "Rent added.")
        |> redirect(to: tenant_path(conn, :show, tenant))
      else
        render(conn, "show.html", tenant: tenant, changeset: changeset)
      end
  end
end

web/views/tenant_view.ex
defmodule HostelManagement.TenantView do
  use HostelManagement.Web, :view
end

web/templates/tenant/edit.html.eex
<h2>Edit tenant</h2>

<%= render "form.html", changeset: @changeset,
                        action: tenant_path(@conn, :update, @tenant) %>

<%= link "Back", to: tenant_path(@conn, :index) %>

web/templates/tenant/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= email_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :contact_number, class: "control-label" %>
    <%= text_input f, :contact_number, class: "form-control" %>
    <%= error_tag f, :contact_number %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/tenant/index.html.eex
<h2>Listing tenants</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Contact number</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for tenant <- @tenants do %>
    <tr>
      <td><%= tenant.name %></td>
      <td><%= tenant.email %></td>
      <td><%= tenant.contact_number %></td>

      <td class="text-right">
        <%= link "Show", to: tenant_path(@conn, :show, tenant), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: tenant_path(@conn, :edit, tenant), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: tenant_path(@conn, :delete, tenant), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New tenant", to: tenant_path(@conn, :new) %>

web/templates/tenant/new.html.eex
<h2>New tenant</h2>

<%= render "form.html", changeset: @changeset,
                        action: tenant_path(@conn, :create) %>

<%= link "Back", to: tenant_path(@conn, :index) %>

web/templates/tenant/rent_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Start Date</label>
    <%= text_input f, :start_date, class: "form-control datepicker" %>
  </div>

  <div class="form-group">
    <label>End Date</label>
    <%= text_input f, :end_date, class: "form-control datepicker" %>
  </div>

  <div class="form-group">
    <%= submit "Add Rent Details", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/tenant/rents.html.eex
<h3> Rents: </h3>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for rent <- @tenant.rents do %>
    <tr>
      <td><%= rent.start_date %></td>
      <td><%= rent.end_date %></td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/tenant/show.html.eex
<h2>Show tenant</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @tenant.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @tenant.email %>
  </li>

  <li>
    <strong>Contact number:</strong>
    <%= @tenant.contact_number %>
  </li>

</ul>

<%= link "Edit", to: tenant_path(@conn, :edit, @tenant) %>
<%= link "Back", to: tenant_path(@conn, :index) %>

<%= render "rent_form.html", tenant: @tenant, changeset: @changeset, action: tenant_tenant_path(@conn, :add_rent, @tenant) %>

<%= render "rents.html", tenant: @tenant %>